#-------------------------------
# General Site Settings

title: Austin Huang
email: austinhu@usc.edu
phone: +1 323 336 0926
address: 3131 McClintock Ave, G161, Los Angeles, CA 90007

menu:
- {name: About Me, link: '/'}
- {name: Projects, link: '/projects/'}

#-------------------------------
# Hero Section

hero:
  hero-title: Austin Huang


#-------------------------------

# About Section
blurb:
  Thanks for visiting my site! I'm a sophomore studying CS/Business Admin at USC. Here's a bit about myself, a couple of projects I've worked on, and topics currently on my mind! ðŸ˜ƒ

blurb-btn-name: Download CV


#-------------------------------

# Portfolio Home Section
portfolio-home-items:
  - image : "assets/images/portfolio/item-1.png"
    url: "#assets/Resume.pdf"
    
  - image : "assets/images/portfolio/item-2.png"
    url: "#"
    
  - image : "assets/images/portfolio/item-3.png"
    url: "#"
    
  - image : "assets/images/portfolio/item-4.png"
    url: "#"
    

# Projects Page

portfolio-items:
  - image : "assets/images/portfolio/pwclogo.jpg"
    url: "https://drive.google.com/file/d/1pnnmZA7FfFzp2n0w04DLK3zwgOzQGpMB/view"

      
  - image : "assets/images/portfolio/boeinglogo.jpg"
    url: "https://docs.google.com/spreadsheets/d/1H2IvRvtk0CfZiT8T-08EJWMlb-v3DXAx-jPyuntaKkY/edit?usp=sharing"

      
  - image : "assets/images/portfolio/ms.jpg"
    url: "https://drive.google.com/file/d/1L_Ubc9JMVG6ex8r41FTPbtg_yr46vvm1/view"
  
